import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import GoogleLogin from '../components/googleLogin';
import Navbar from '../components/navbar/navbar';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Streamn</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <Navbar />
        <GoogleLogin />
      </main>
    </div>
  );
};

export default Home;
