import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Navbar from '../components/navbar/navbar';
import { useEffect } from 'react';
import { getCookies, validateSignInCookies } from '../utils/auth';
import { getUserData } from '../services/user';
import { useDispatch } from 'react-redux';
import { bindActionCreators } from 'redux';
import { actionCreators } from '../state';

const Home: NextPage = () => {
  const dispatch = useDispatch();
  const { setUser } = bindActionCreators(actionCreators, dispatch);

  useEffect(() => {
    authenticate();
  }, []); // eslint-disable-line react-hooks/exhaustive-deps

  const authenticate = async () => {
    const { profileId, sessionToken, sessionExpirationTS } = getCookies();
    if (
      profileId &&
      sessionToken &&
      validateSignInCookies(profileId, sessionToken, sessionExpirationTS)
    ) {
      const [response, error] = await getUserData(profileId, sessionToken);
      if (response?.data) {
        setUser(response.data);
      }
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Streamn</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <Navbar />
      </main>
    </div>
  );
};

export default Home;
